
import java.sql.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * regester.java
 *
 * Created on Nov 2, 2006, 12:34:45 AM
 */

/**
 *
 * @author Student
 */
@SuppressWarnings("serial")
public class regester extends javax.swing.JFrame {
private int a=0,d=0,m=0,y=0;
@SuppressWarnings("FieldMayBeFinal")
private boolean a1=true,a2=false,a3=false,a4=false,a5=false,a6=false,a7=false,a8=false,a9=false,a10=false,a11=false,a12=false;
    /** Creates new form regester */
    public regester() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alert = new javax.swing.JOptionPane();
        TOA = new javax.swing.ButtonGroup();
        MOO = new javax.swing.ButtonGroup();
        pHelp = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        pGI = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        showdate1 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        dd1 = new javax.swing.JComboBox();
        mm1 = new javax.swing.JComboBox();
        yyyy1 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        strNOI1 = new javax.swing.JTextField();
        strMName1 = new javax.swing.JTextField();
        strFName1 = new javax.swing.JTextField();
        strName1 = new javax.swing.JTextField();
        strCO1 = new javax.swing.JTextField();
        strCR1 = new javax.swing.JTextField();
        strCM1 = new javax.swing.JTextField();
        strAR1 = new javax.swing.JTextField();
        strAO1 = new javax.swing.JTextField();
        strEQ1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        DG1 = new javax.swing.JButton();
        pTOA1 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        pN1 = new javax.swing.JPanel();
        CN1 = new javax.swing.JCheckBox();
        NName1 = new javax.swing.JLabel();
        Naccno1 = new javax.swing.JLabel();
        NCNo1 = new javax.swing.JLabel();
        NAddress1 = new javax.swing.JLabel();
        strNName1 = new javax.swing.JTextField();
        strNCNo1 = new javax.swing.JTextField();
        strNAccno1 = new javax.swing.JTextField();
        strNAdd1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Naccnovornv1 = new javax.swing.JLabel();
        pDOM1 = new javax.swing.JPanel();
        strper6 = new javax.swing.JTextField();
        strper7 = new javax.swing.JTextField();
        strper8 = new javax.swing.JTextField();
        strper9 = new javax.swing.JTextField();
        strper10 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        sigPer6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        sigPer7 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        sigPer8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        sigPer9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        sigPer10 = new javax.swing.JTextArea();
        DDOM1 = new javax.swing.JButton();
        pMOO1 = new javax.swing.JPanel();
        DMOO1 = new javax.swing.JButton();
        RMOOSelf1 = new javax.swing.JRadioButton();
        RMOOJoint1 = new javax.swing.JRadioButton();
        RMOOSpecify1 = new javax.swing.JRadioButton();
        RMOOESur1 = new javax.swing.JRadioButton();
        RMOOASur1 = new javax.swing.JRadioButton();
        strmoospecify1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        javax.swing.GroupLayout pHelpLayout = new javax.swing.GroupLayout(pHelp);
        pHelp.setLayout(pHelpLayout);
        pHelpLayout.setHorizontalGroup(
            pHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 81, Short.MAX_VALUE)
        );
        pHelpLayout.setVerticalGroup(
            pHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pGI.setBorder(javax.swing.BorderFactory.createTitledBorder("General Information :"));

        jLabel22.setText("Enter your name");

        jLabel23.setText("Enter your father's name");

        jLabel24.setText("Enter your mother's name");

        jLabel25.setText("Choose your date of birth");

        jLabel26.setText("dd/mm/yyyy:");

        jLabel27.setText("Contact No:");

        jLabel28.setText("Residence:");

        jLabel29.setText("Office:");

        jLabel30.setText("Mobile:");

        jLabel31.setText("Address:");

        jLabel32.setText("Residence:");

        jLabel33.setText("Office:");

        showdate1.setText("--/--/----");

        jLabel34.setText("Studying at:");

        jLabel35.setText("Education Qualification:");

        dd1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dd", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dd1ActionPerformed(evt);
            }
        });
        dd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                dd1FocusLost(evt);
            }
        });

        mm1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "mm", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        mm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mm1ActionPerformed(evt);
            }
        });
        mm1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mm1FocusLost(evt);
            }
        });

        yyyy1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "yyyy", "1900" }));
        yyyy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yyyy1ActionPerformed(evt);
            }
        });
        yyyy1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                yyyy1FocusLost(evt);
            }
        });

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel36.setText("to year");

        strName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strName1ActionPerformed(evt);
            }
        });
        strName1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                strName1FocusLost(evt);
            }
        });

        strCO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strCO1ActionPerformed(evt);
            }
        });

        strAR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strAR1ActionPerformed(evt);
            }
        });

        strEQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strEQ1ActionPerformed(evt);
            }
        });

        jLabel37.setText("from year");

        DG1.setText("DONE");

        javax.swing.GroupLayout pGILayout = new javax.swing.GroupLayout(pGI);
        pGI.setLayout(pGILayout);
        pGILayout.setHorizontalGroup(
            pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGILayout.createSequentialGroup()
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pGILayout.createSequentialGroup()
                        .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addGroup(pGILayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel31)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33)))
                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(pGILayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pGILayout.createSequentialGroup()
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGILayout.createSequentialGroup()
                        .addComponent(dd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yyyy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGILayout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(strName1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strFName1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strMName1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strCR1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strCO1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strCM1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strAR1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strAO1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strNOI1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(strEQ1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DG1))))
        );
        pGILayout.setVerticalGroup(
            pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pGILayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strFName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strMName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mm1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yyyy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(showdate1))
                .addGap(6, 6, 6)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strCR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strCO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strCM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strAR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strAO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strNOI1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36))
                .addGap(18, 18, 18)
                .addGroup(pGILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strEQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35))
                .addGap(21, 21, 21)
                .addComponent(DG1))
        );

        pTOA1.setBorder(javax.swing.BorderFactory.createTitledBorder("Type of account you want to create :"));

        jRadioButton5.setText("FIXED DEPOSITE");

        jRadioButton6.setText("R DEPOSITE");

        jRadioButton7.setText("CURRENT ACCOUNT");

        jRadioButton8.setText("SAVING ACCOUNT");

        jButton3.setText("DONE");

        javax.swing.GroupLayout pTOA1Layout = new javax.swing.GroupLayout(pTOA1);
        pTOA1.setLayout(pTOA1Layout);
        pTOA1Layout.setHorizontalGroup(
            pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTOA1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6))
                .addGap(70, 70, 70)
                .addGroup(pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        pTOA1Layout.setVerticalGroup(
            pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTOA1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTOA1Layout.createSequentialGroup()
                        .addGroup(pTOA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pTOA1Layout.createSequentialGroup()
                                .addComponent(jRadioButton7)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton8))
                            .addGroup(pTOA1Layout.createSequentialGroup()
                                .addComponent(jRadioButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton6)))
                        .addContainerGap(17, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pTOA1Layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addComponent(jButton3))))
        );

        pN1.setBorder(javax.swing.BorderFactory.createTitledBorder("NOMINATION :"));

        CN1.setText("NOMINATION REQUIRED");
        CN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CN1ActionPerformed(evt);
            }
        });

        NName1.setText("NAME :");

        Naccno1.setText("ACCOUNT NUMBER");

        NCNo1.setText("CONTACT NO :");

        NAddress1.setText("ADDRESS :");

        jButton4.setText("DONE");

        javax.swing.GroupLayout pN1Layout = new javax.swing.GroupLayout(pN1);
        pN1.setLayout(pN1Layout);
        pN1Layout.setHorizontalGroup(
            pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pN1Layout.createSequentialGroup()
                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CN1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pN1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NName1)
                            .addComponent(NCNo1)
                            .addComponent(Naccno1)
                            .addComponent(NAddress1))
                        .addGap(53, 53, 53)
                        .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(strNAdd1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(strNName1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addGroup(pN1Layout.createSequentialGroup()
                                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(strNCNo1)
                                    .addComponent(strNAccno1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton4)
                                    .addComponent(Naccnovornv1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        pN1Layout.setVerticalGroup(
            pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pN1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CN1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NName1)
                    .addComponent(strNName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strNAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strNAccno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Naccno1)
                    .addComponent(Naccnovornv1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strNCNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NCNo1)
                    .addComponent(jButton4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pDOM1.setBorder(javax.swing.BorderFactory.createTitledBorder("DETAILS OF MEMBER :"));

        strper6.setText("jTextField1");

        jLabel38.setText("PERSON 1");

        jLabel39.setText("PERSON 1");

        jLabel40.setText("PERSON 1");

        jLabel41.setText("PERSON 1");

        jLabel42.setText("PERSON 1");

        jScrollPane7.setMinimumSize(new java.awt.Dimension(5, 5));
        jScrollPane7.setWheelScrollingEnabled(false);

        sigPer6.setColumns(20);
        sigPer6.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        sigPer6.setLineWrap(true);
        sigPer6.setRows(5);
        sigPer6.setText("CLICK HERE \nTO INSERT\nSIGNATURE OF\nPERSON1");
        jScrollPane7.setViewportView(sigPer6);

        jScrollPane8.setMinimumSize(new java.awt.Dimension(5, 5));
        jScrollPane8.setWheelScrollingEnabled(false);

        sigPer7.setColumns(20);
        sigPer7.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        sigPer7.setLineWrap(true);
        sigPer7.setRows(5);
        sigPer7.setText("CLICK HERE \nTO INSERT\nSIGNATURE OF\nPERSON2");
        jScrollPane8.setViewportView(sigPer7);

        jScrollPane9.setMinimumSize(new java.awt.Dimension(5, 5));
        jScrollPane9.setWheelScrollingEnabled(false);

        sigPer8.setColumns(20);
        sigPer8.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        sigPer8.setLineWrap(true);
        sigPer8.setRows(5);
        sigPer8.setText("CLICK HERE \nTO INSERT\nSIGNATURE OF\nPERSON3");
        jScrollPane9.setViewportView(sigPer8);

        jScrollPane10.setMinimumSize(new java.awt.Dimension(5, 5));
        jScrollPane10.setWheelScrollingEnabled(false);

        sigPer9.setColumns(20);
        sigPer9.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        sigPer9.setLineWrap(true);
        sigPer9.setRows(5);
        sigPer9.setText("CLICK HERE \nTO INSERT\nSIGNATURE OF\nPERSON4");
        jScrollPane10.setViewportView(sigPer9);

        jScrollPane11.setMinimumSize(new java.awt.Dimension(5, 5));
        jScrollPane11.setWheelScrollingEnabled(false);

        sigPer10.setColumns(20);
        sigPer10.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
        sigPer10.setLineWrap(true);
        sigPer10.setRows(5);
        sigPer10.setText("CLICK HERE \nTO INSERT\nSIGNATURE OF\nPERSON5");
        jScrollPane11.setViewportView(sigPer10);

        DDOM1.setText("DONE");

        javax.swing.GroupLayout pDOM1Layout = new javax.swing.GroupLayout(pDOM1);
        pDOM1.setLayout(pDOM1Layout);
        pDOM1Layout.setHorizontalGroup(
            pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDOM1Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(strper6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pDOM1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(strper7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel39)))
                    .addGroup(pDOM1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, 0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, 0, 0, Short.MAX_VALUE)
                    .addComponent(strper8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jLabel40))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane10, 0, 0, Short.MAX_VALUE)
                    .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(strper9, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jLabel41)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(strper10, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane11, 0, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDOM1Layout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .addComponent(DDOM1))
        );
        pDOM1Layout.setVerticalGroup(
            pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDOM1Layout.createSequentialGroup()
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel39)
                    .addComponent(jLabel40)
                    .addComponent(jLabel41)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(strper6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strper7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strper8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strper9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(strper10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDOM1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DDOM1))
        );

        pMOO1.setBorder(javax.swing.BorderFactory.createTitledBorder("MODE OF OPPERATION :"));

        DMOO1.setText("DONE");

        RMOOSelf1.setText("SELF");

        RMOOJoint1.setText("JOINTLY");

        RMOOSpecify1.setText("ANY OTHER(SPECIFY)");

        RMOOESur1.setText("EITHER SURVIVOR");

        RMOOASur1.setText("ANY ONE OF SURVIVOR");

        javax.swing.GroupLayout pMOO1Layout = new javax.swing.GroupLayout(pMOO1);
        pMOO1.setLayout(pMOO1Layout);
        pMOO1Layout.setHorizontalGroup(
            pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMOO1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pMOO1Layout.createSequentialGroup()
                        .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RMOOSelf1)
                            .addComponent(RMOOJoint1)
                            .addComponent(RMOOSpecify1))
                        .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pMOO1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RMOOASur1)
                                    .addComponent(RMOOESur1)))
                            .addGroup(pMOO1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(strmoospecify1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(208, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMOO1Layout.createSequentialGroup()
                        .addGap(0, 509, Short.MAX_VALUE)
                        .addComponent(DMOO1))))
        );
        pMOO1Layout.setVerticalGroup(
            pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMOO1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMOOSelf1)
                    .addComponent(RMOOESur1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMOOJoint1)
                    .addComponent(RMOOASur1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pMOO1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RMOOSpecify1)
                    .addComponent(strmoospecify1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(DMOO1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pDOM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pGI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pTOA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pMOO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pGI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pTOA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pMOO1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pDOM1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane6.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pHelp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("static-access")
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
String mmddyyyy="";
        if(a==0){this.setVisible(false);++a;mmddyyyy=alert.showInputDialog(null, "Please Enter the date \n dd/mm/yyyy");this.setVisible(true);}

String year=mmddyyyy.substring(6,10);
        for(a=1901;a<=Integer.parseInt(year);++a){
       }
pGI.setVisible(a1);


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void dd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dd1ActionPerformed

        // TODO add your handling code here:
}//GEN-LAST:event_dd1ActionPerformed

    private void dd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dd1FocusLost
        d=dd.getSelectedIndex();
        showdate.setText(""+d+"/"+m+"/"+y+"");
        // TODO add your handling code here:
}//GEN-LAST:event_dd1FocusLost

    private void mm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mm1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_mm1ActionPerformed

    private void mm1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mm1FocusLost
        m=mm.getSelectedIndex();   showdate.setText(""+d+"/"+m+"/"+y+"");   // TODO add your handling code here:
}//GEN-LAST:event_mm1FocusLost

    private void yyyy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yyyy1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_yyyy1ActionPerformed

    private void yyyy1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_yyyy1FocusLost
        y=yyyy.getSelectedIndex(); y=y+1900; --y; showdate.setText(""+d+"/"+m+"/"+y+"");   // TODO add your handling code here:
}//GEN-LAST:event_yyyy1FocusLost

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jComboBox6ActionPerformed

    private void strName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strName1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_strName1ActionPerformed

    private void strName1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_strName1FocusLost
        strName.setText(strName.getText().toUpperCase());        // TODO add your handling code here:
}//GEN-LAST:event_strName1FocusLost

    private void strCO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strCO1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_strCO1ActionPerformed

    private void strAR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strAR1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_strAR1ActionPerformed

    private void strEQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strEQ1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_strEQ1ActionPerformed

    private void CN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CN1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_CN1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CN1;
    private javax.swing.JButton DDOM1;
    private javax.swing.JButton DG1;
    private javax.swing.JButton DMOO1;
    private javax.swing.ButtonGroup MOO;
    private javax.swing.JLabel NAddress1;
    private javax.swing.JLabel NCNo1;
    private javax.swing.JLabel NName1;
    private javax.swing.JLabel Naccno1;
    private javax.swing.JLabel Naccnovornv1;
    private javax.swing.JRadioButton RMOOASur1;
    private javax.swing.JRadioButton RMOOESur1;
    private javax.swing.JRadioButton RMOOJoint1;
    private javax.swing.JRadioButton RMOOSelf1;
    private javax.swing.JRadioButton RMOOSpecify1;
    private javax.swing.ButtonGroup TOA;
    private javax.swing.JOptionPane alert;
    private javax.swing.JComboBox dd1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JComboBox mm1;
    private javax.swing.JPanel pDOM1;
    private javax.swing.JPanel pGI;
    private javax.swing.JPanel pHelp;
    private javax.swing.JPanel pMOO1;
    private javax.swing.JPanel pN1;
    private javax.swing.JPanel pTOA1;
    private javax.swing.JLabel showdate1;
    private javax.swing.JTextArea sigPer10;
    private javax.swing.JTextArea sigPer6;
    private javax.swing.JTextArea sigPer7;
    private javax.swing.JTextArea sigPer8;
    private javax.swing.JTextArea sigPer9;
    private javax.swing.JTextField strAO1;
    private javax.swing.JTextField strAR1;
    private javax.swing.JTextField strCM1;
    private javax.swing.JTextField strCO1;
    private javax.swing.JTextField strCR1;
    private javax.swing.JTextField strEQ1;
    private javax.swing.JTextField strFName1;
    private javax.swing.JTextField strMName1;
    private javax.swing.JTextField strNAccno1;
    private javax.swing.JTextField strNAdd1;
    private javax.swing.JTextField strNCNo1;
    private javax.swing.JTextField strNName1;
    private javax.swing.JTextField strNOI1;
    private javax.swing.JTextField strName1;
    private javax.swing.JTextField strmoospecify1;
    private javax.swing.JTextField strper10;
    private javax.swing.JTextField strper6;
    private javax.swing.JTextField strper7;
    private javax.swing.JTextField strper8;
    private javax.swing.JTextField strper9;
    private javax.swing.JComboBox yyyy1;
    // End of variables declaration//GEN-END:variables

}
